### ISSUE TITLE
Nonce / JWT - No Documents 

### ISSUE THREAD

**Issue by michael-alexcan** [egany/ultimate-wp-rest-api#1]
Hello,
Am trying to get a nonce but i keep getting the fallowing error:

`{
    "code": "rest_user_nonce_disabled",
    "message": "Nonce code is not available.",
    "data": {
        "status": 403
    }
}`

**Comment by egany** [comment]
I recommend you use JWT instead of get nonce as default.

**Comment by RigTag** [comment]
> I recommend you use JWT instead of get nonce as default.

can you recommend me a source to use or a tutorial to get my React Native app working with your rest-api and JWT?
i have the it configured firing a token but i dont know where to start from this point?

`{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvbW9yZWluNC5jb20iLCJpYXQiOjE1NDU5NjY2NDYsIm5iZiI6MTUTk2NjY0NiwiZXhwIjoxNTQ2NTcxNDQ2LCJkYXRhIjp7InVzZXIiOnsiaWQiOiI1NyJ9fX0.Zh16RxJSahLOX8aA22kYx1ZIbG_AGXVnvWMVUmtW6y8",
    "user_email": "facebook@gmail.com",
    "user_nicename": "facebook",
    "user_display_name": "face"
}`

**Comment by egany** [comment]
Hi there,
I don't have open source React Native to do that but you can consider this template: https://codecanyon.net/item/gikapp-react-native-full-application/19465924

I have RN code like this:
```
//Auth by JWT
  postLoginByJWT(bodyJson) {
    let params = {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(bodyJson)
    }
    // console.log(params)
    let baseUri = `${this.baseApi()}/users/me/login`
    return this.fetchData(baseUri, params)
  },

  getUserInfoByJWT(token) {
    let params = {
      method: 'GET',
      headers: {
        'Authorization':`Bearer ${token}`
      }
    }
    console.log("getUserInfoByJWT params: ", params)
    return this.fetchData(`${this.baseApi()}/users/me/`, params)
  },
```

**Comment by RigTag** [comment]
Thanks you replaying.
what i need is the registration part please? 
So the user is not logged in how do i get a him logged in using the rest API and getting a token without exposing admin?

> ill be creating a nice looking Documents for you to add to this plugin if you like..
